# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Project\vt_ginkgo_examples\trunk\PyQT4\Ginkgo I2C\PyQT4_USB_I2C_AT24C02\MainWindow.ui'
#
# Created: Thu Nov 13 12:02:55 2014
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(474, 251)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(222, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.deviceIndexCmboBox = QtGui.QComboBox(self.groupBox)
        self.deviceIndexCmboBox.setObjectName(_fromUtf8("deviceIndexCmboBox"))
        self.deviceIndexCmboBox.addItem(_fromUtf8(""))
        self.deviceIndexCmboBox.addItem(_fromUtf8(""))
        self.deviceIndexCmboBox.addItem(_fromUtf8(""))
        self.deviceIndexCmboBox.addItem(_fromUtf8(""))
        self.deviceIndexCmboBox.addItem(_fromUtf8(""))
        self.deviceIndexCmboBox.addItem(_fromUtf8(""))
        self.deviceIndexCmboBox.addItem(_fromUtf8(""))
        self.deviceIndexCmboBox.addItem(_fromUtf8(""))
        self.deviceIndexCmboBox.addItem(_fromUtf8(""))
        self.deviceIndexCmboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.deviceIndexCmboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.channelIndexComboBox = QtGui.QComboBox(self.groupBox)
        self.channelIndexComboBox.setObjectName(_fromUtf8("channelIndexComboBox"))
        self.channelIndexComboBox.addItem(_fromUtf8(""))
        self.channelIndexComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.channelIndexComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.clockSpeedComboBox = QtGui.QComboBox(self.groupBox)
        self.clockSpeedComboBox.setObjectName(_fromUtf8("clockSpeedComboBox"))
        self.clockSpeedComboBox.addItem(_fromUtf8(""))
        self.clockSpeedComboBox.addItem(_fromUtf8(""))
        self.clockSpeedComboBox.addItem(_fromUtf8(""))
        self.clockSpeedComboBox.addItem(_fromUtf8(""))
        self.clockSpeedComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.clockSpeedComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.slaveAddrLineEdit = QtGui.QLineEdit(self.groupBox)
        self.slaveAddrLineEdit.setObjectName(_fromUtf8("slaveAddrLineEdit"))
        self.horizontalLayout_4.addWidget(self.slaveAddrLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_9.addWidget(self.label_7)
        self.subAddrLineEdit = QtGui.QLineEdit(self.groupBox)
        self.subAddrLineEdit.setObjectName(_fromUtf8("subAddrLineEdit"))
        self.horizontalLayout_9.addWidget(self.subAddrLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.readDataTextBrowser = QtGui.QTextBrowser(self.groupBox_2)
        self.readDataTextBrowser.setObjectName(_fromUtf8("readDataTextBrowser"))
        self.gridLayout_2.addWidget(self.readDataTextBrowser, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.writeDataLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.writeDataLineEdit.setObjectName(_fromUtf8("writeDataLineEdit"))
        self.horizontalLayout_5.addWidget(self.writeDataLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.readDataCountLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.readDataCountLineEdit.setObjectName(_fromUtf8("readDataCountLineEdit"))
        self.horizontalLayout_6.addWidget(self.readDataCountLineEdit)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.readPushButton = QtGui.QPushButton(self.centralwidget)
        self.readPushButton.setObjectName(_fromUtf8("readPushButton"))
        self.horizontalLayout_7.addWidget(self.readPushButton)
        self.writePushButton = QtGui.QPushButton(self.centralwidget)
        self.writePushButton.setObjectName(_fromUtf8("writePushButton"))
        self.horizontalLayout_7.addWidget(self.writePushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "USB-I2C AT24C02", None))
        self.groupBox.setTitle(_translate("MainWindow", "Setting", None))
        self.label_2.setText(_translate("MainWindow", "Device Index:", None))
        self.deviceIndexCmboBox.setItemText(0, _translate("MainWindow", "0", None))
        self.deviceIndexCmboBox.setItemText(1, _translate("MainWindow", "1", None))
        self.deviceIndexCmboBox.setItemText(2, _translate("MainWindow", "2", None))
        self.deviceIndexCmboBox.setItemText(3, _translate("MainWindow", "3", None))
        self.deviceIndexCmboBox.setItemText(4, _translate("MainWindow", "4", None))
        self.deviceIndexCmboBox.setItemText(5, _translate("MainWindow", "5", None))
        self.deviceIndexCmboBox.setItemText(6, _translate("MainWindow", "6", None))
        self.deviceIndexCmboBox.setItemText(7, _translate("MainWindow", "7", None))
        self.deviceIndexCmboBox.setItemText(8, _translate("MainWindow", "8", None))
        self.deviceIndexCmboBox.setItemText(9, _translate("MainWindow", "9", None))
        self.label_3.setText(_translate("MainWindow", "Channel Index:", None))
        self.channelIndexComboBox.setItemText(0, _translate("MainWindow", "0", None))
        self.channelIndexComboBox.setItemText(1, _translate("MainWindow", "1", None))
        self.label_4.setText(_translate("MainWindow", "Clock Speed:", None))
        self.clockSpeedComboBox.setItemText(0, _translate("MainWindow", "400Kbps", None))
        self.clockSpeedComboBox.setItemText(1, _translate("MainWindow", "200Kbps", None))
        self.clockSpeedComboBox.setItemText(2, _translate("MainWindow", "100Kbps", None))
        self.clockSpeedComboBox.setItemText(3, _translate("MainWindow", "50Kbps", None))
        self.clockSpeedComboBox.setItemText(4, _translate("MainWindow", "25Kbps", None))
        self.label_5.setText(_translate("MainWindow", "Slave Addr(Hex):", None))
        self.slaveAddrLineEdit.setText(_translate("MainWindow", "A0", None))
        self.label_7.setText(_translate("MainWindow", "  Sub Addr(Hex):", None))
        self.subAddrLineEdit.setText(_translate("MainWindow", "00", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Read Data(Hex)", None))
        self.label.setText(_translate("MainWindow", "Write Data(Hex):", None))
        self.writeDataLineEdit.setText(_translate("MainWindow", "11 22 33 44 55 66 77 88", None))
        self.label_6.setText(_translate("MainWindow", "Read Data Count:", None))
        self.readDataCountLineEdit.setText(_translate("MainWindow", "8", None))
        self.readPushButton.setText(_translate("MainWindow", "Read", None))
        self.writePushButton.setText(_translate("MainWindow", "Write", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

